version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest

#dependencies:
#  galaxy: requirements.yml


additional_build_steps:
  prepend_base:
    - COPY collections/* /usr/share/ansible/collections/