---
# tasks file for aap-config
- name: Create a new token using controller username/password
  ansible.controller.token:
    description: 'Creating token to test controller jobs'
    scope: "write"
    state: present
    controller_host: "{{ controller_hostname }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
  register: token
- name: Show token
  ansible.builtin.debug:
    msg: "{{ token }}"

- name: Load manifest
  infra.aap_configuration.controller_license:
    controller_host: "{{ controller_hostname }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    manifest_file: "files/aap-manifest.zip"
    state: present
    